version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
